# numpy == list but numpy faster then list ,,,    list as a array 

# numpy

In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a

array([1, 2, 3])

In [7]:
a.shape

(3,)

In [8]:
a.ndim


1

In [12]:
b=np.array(5)

In [13]:
b

array(5)

In [15]:
b.ndim

0

In [22]:
a1=np.array( (  [1,2,3,4] , [5,6,7,8] ,  [9,10,11,12]  ,[13,14,15,16]   ) )

In [47]:
a1[1,1]

6

In [23]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [92]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [49]:
a1[1:4 ]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [94]:
a1[1:3,1:3] = [  [9,10] , [11 ,12]  ]

In [95]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  9, 10,  8],
       [ 9, 11, 12, 12],
       [13, 14, 15, 16]])

In [52]:
a1[1:2 ,2 ]

array([7])

In [58]:
d=a1[1:3,1:3]

In [59]:
d

array([[ 6,  7],
       [10, 11]])

In [60]:
d.size

4

In [24]:
type(a1)

numpy.ndarray

In [25]:
a3=np.array( [  [  [1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9]  ]   ]  )

In [61]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [62]:
a3[0,1,1]

5

In [26]:
type(a3)

numpy.ndarray

In [27]:
a3.dtype

dtype('int32')

In [28]:
a3.size

27

In [29]:
a3.shape

(3, 3, 3)

In [30]:
a31=np.array( [  [  [1],[2],[3]   ]  , [  [4],[5],[6]    ]  ,  [   [7],[8],[9]  ]   ]  )

In [31]:
a31

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [63]:
a31[::]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [32]:
type(a31)

numpy.ndarray

In [33]:
a31.size

9

In [34]:
a4=np.array( [  [  [ [1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9] ]   ,  [ [1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9] ]  ,   [ [1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9] ]   ]  , [  [ [1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9] ]   ,  [ [1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9] ]  ,  [ [1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9] ]    ]  ,  [   [[1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9]]    ,  [[1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9]]  ,   [[1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9]]  ]   ]  )

In [35]:
a4

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

      

In [40]:
a4.size

243

In [38]:
a4.ndim

4

In [41]:
a4.shape

(3, 9, 3, 3)

In [45]:
a4[1,1,1,1]

5

In [ ]:
a21=a2

In [68]:
a13=np.array( [  [  [4,5,6,5],[7,8,9,4]   ]  , [  [1,2,4,3],[4,5,6,1]    ]     ]  )

In [69]:
a13

array([[[4, 5, 6, 5],
        [7, 8, 9, 4]],

       [[1, 2, 4, 3],
        [4, 5, 6, 1]]])

In [76]:
a13[1,1,1]

5

In [85]:
a13[1,1,1] =  1

In [86]:
a13

array([[[4, 5, 6, 5],
        [7, 8, 9, 4]],

       [[1, 2, 4, 3],
        [4, 1, 6, 1]]])

In [81]:
a13[1,1,1]

5

In [73]:
x=a13[  (0,0,0,1,1,1) , (0,0,1,0,1,1)  ,  (0,3,2,3,0,1) ]

In [75]:
x

array([4, 5, 9, 3, 4, 5])

In [90]:
a13[  (0,0,0,1,1,1) , (0,0,1,0,1,1)  ,  (0,3,2,3,0,1) ] = 1

In [91]:
a13

array([[[1, 5, 6, 1],
        [7, 8, 1, 4]],

       [[1, 2, 4, 1],
        [1, 1, 6, 1]]])

In [74]:
x.ndim

1

In [87]:
x.size

6