In [1]:
list1= [1,2,3,4,5]

In [2]:
list2= [6,7,8,9,10]

In [3]:
for i,j in zip(list1,list2):
    print(i,j)
    

1 6
2 7
3 8
4 9
5 10


In [2]:
import numpy as np

In [37]:
import math as np

In [42]:
a4=np.array( [  [  [ [1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9] ]   ,  [ [1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9] ]  ,   [ [1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9] ]   ]  , [  [ [1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9] ]   ,  [ [1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9] ]  ,  [ [1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9] ]    ]  ,  [   [[1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9]]    ,  [[1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9]]  ,   [[1,2,3],[4,5,6],[7,8,9]   ]  , [  [1,2,3],[4,5,6],[7,8,9]    ]  ,  [   [1,2,3],[4,5,6],[7,8,9]]  ]   ]  )

In [11]:
a1=np.array( (  [1,2,3,4] , [5,6,7,8] ,  [9,10,11,12]  ,[13,14,15,16]   ) )

In [43]:
a1

array([[  1,   2,   3,   4],
       [  5, 100,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16]])

In [13]:
b=a1.copy()

In [14]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
b[1,1]

6

In [16]:
b[1,1]= 20

In [17]:
b

array([[ 1,  2,  3,  4],
       [ 5, 20,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
c=a1

In [20]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
c[1,1]

6

In [22]:
c[1,1]=66

In [23]:
c

array([[ 1,  2,  3,  4],
       [ 5, 66,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [24]:
a1

array([[ 1,  2,  3,  4],
       [ 5, 66,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
d=a1.view()

In [26]:
d

array([[ 1,  2,  3,  4],
       [ 5, 66,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [27]:
d[1,1]

66

In [28]:
d[1,1]=100

In [29]:
d

array([[  1,   2,   3,   4],
       [  5, 100,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16]])

In [30]:
a1

array([[  1,   2,   3,   4],
       [  5, 100,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16]])

In [31]:
e=a1.view()

In [32]:
e

array([[  1,   2,   3,   4],
       [  5, 100,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16]])

In [33]:
e[1,1]

100

In [34]:
e[1,1]==1111

False

In [35]:
e[1,1]==100

True

In [6]:
aa=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [7]:
aa

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [47]:
aa.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [48]:
aa.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [49]:
aa.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [50]:
aa.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [51]:
aa.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [52]:
aa.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
aa.reshape(1,1,12)

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]])

In [54]:
aa.reshape(1,12,1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]]])

In [55]:
aa.reshape(12,1,1)

array([[[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]]])

In [56]:
aa.reshape(12,1,1,1)

array([[[[ 1]]],


       [[[ 2]]],


       [[[ 3]]],


       [[[ 4]]],


       [[[ 5]]],


       [[[ 6]]],


       [[[ 7]]],


       [[[ 8]]],


       [[[ 9]]],


       [[[10]]],


       [[[11]]],


       [[[12]]]])

In [57]:
aa.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
aa.reshape(2,2,3,1)

array([[[[ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6]]],


       [[[ 7],
         [ 8],
         [ 9]],

        [[10],
         [11],
         [12]]]])

In [8]:
x=aa.reshape(4,3)

In [9]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [64]:
aa

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [69]:
for i in np.nditer(x):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [10]:
for i in np.ndenumerate(x):
    print(i)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((1, 0), 4)
((1, 1), 5)
((1, 2), 6)
((2, 0), 7)
((2, 1), 8)
((2, 2), 9)
((3, 0), 10)
((3, 1), 11)
((3, 2), 12)


In [15]:
for i,j in np.ndenumerate(x):
    print(i)
    xx1=i
    print(xx1)
    print(j)

(0, 0)
(0, 0)
1
(0, 1)
(0, 1)
2
(0, 2)
(0, 2)
3
(1, 0)
(1, 0)
4
(1, 1)
(1, 1)
5
(1, 2)
(1, 2)
6
(2, 0)
(2, 0)
7
(2, 1)
(2, 1)
8
(2, 2)
(2, 2)
9
(3, 0)
(3, 0)
10
(3, 1)
(3, 1)
11
(3, 2)
(3, 2)
12


In [13]:
xx1

(3, 2)