In [1]:
import numpy as np

In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.zeros((3,3),'c')

array([[b'', b'', b''],
       [b'', b'', b''],
       [b'', b'', b'']], dtype='|S1')

In [29]:
np.zeros_like((3,3))

array([0, 0])

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [58]:
np.ones((3,3))

TypeError: Cannot interpret '15' as a data type

In [39]:
np.zeros( (2,) , dtype = [ ('x', 'i4') , ('y', 'i4') ] )

array([(0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

In [36]:
np.zeros((2,))

array([0., 0.])

In [51]:
dtype=[ ('x', 'i4'), ('y', 'i4') ]

In [52]:
dtype

[('x', 'i4'), ('y', 'i4')]

In [50]:
np.ones((4,4) , dtype= np.int8)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [54]:
np.ones((4,4 ), dtype= "int8")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [63]:
np.ones((4,4 ),'c')

array([[b'1', b'1', b'1', b'1'],
       [b'1', b'1', b'1', b'1'],
       [b'1', b'1', b'1', b'1'],
       [b'1', b'1', b'1', b'1']], dtype='|S1')

In [69]:
a1=np.ones( (4 , 4 )  )

In [70]:
a1*13

array([[13., 13., 13., 13.],
       [13., 13., 13., 13.],
       [13., 13., 13., 13.],
       [13., 13., 13., 13.]])

In [72]:
a=np.array(([1,2] , [3,4] ))

In [73]:
b=np.array(([5,6] , [7,8]))

In [74]:
a

array([[1, 2],
       [3, 4]])

In [75]:
b

array([[5, 6],
       [7, 8]])

In [78]:
np.add(a,b)

array([[ 6,  8],
       [10, 12]])

In [81]:
np.add(a,a)

array([[2, 4],
       [6, 8]])

In [90]:
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

In [92]:
np.subtract(a,b)

array([[-4, -4],
       [-4, -4]])

In [94]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [131]:
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [96]:
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [106]:
c=np.array(([1,2,3],[4,5,6,]))

In [107]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
d=np.array(([ [1,2] , [4,5]  ]  , [ [1,2] , [4,5]  ]))

In [120]:
d.size

8

In [121]:
d.shape

(2, 2, 2)

In [122]:
d

array([[[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]]])

In [126]:
a

array([[1, 2],
       [3, 4]])

In [134]:
np.concatenate((a,d),axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)

In [110]:
np.concatenate((b,c),axis=1)

array([[5, 6, 1, 2, 3],
       [7, 8, 4, 5, 6]])

In [129]:
np.concatenate((b,d),axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [85]:
a+b

array([[ 6,  8],
       [10, 12]])

In [80]:
np.sum(a)

10

In [30]:
np.zeros_like(5)

array(0)

In [55]:
np.full((3,3),15)

array([[15, 15, 15],
       [15, 15, 15],
       [15, 15, 15]])

In [27]:
np.empty((3,3) )

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 4.84184333e-321],
       [1.05699242e-307, 8.01097888e-307, 4.17706815e+199]])

In [9]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [ ]:
e=np.array(([ [ [1,2] , [4,5]  ]  , [ [1,2] , [4,5]  ] ] , [ [1,2] , [4,5]  ]  , [ [1,2] , [4,5]  ] ]  ]  , [ [ [1,2] , [4,5]  ]  , [ [1,2] , [4,5]  ] ] , [ [1,2] , [4,5]  ]  , [ [1,2] , [4,5]  ] ]  ]))

In [137]:
e=np.array(([1,2,3,4] , [5,6,7,8] , [1,2,3,4] , [5,6,7,8]))

In [138]:
e

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [139]:
np.array_split(e,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]])]

In [170]:
np.array_split( e,5, axis = 1)

[array([[1],
        [5],
        [1],
        [5]]),
 array([[2],
        [6],
        [2],
        [6]]),
 array([[3],
        [7],
        [3],
        [7]]),
 array([[4],
        [8],
        [4],
        [8]]),
 array([], shape=(4, 0), dtype=int32)]

In [184]:
np.split(e,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]])]

In [149]:
j1,j2,j3=np.array_split(e,3)

In [150]:
j1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [151]:
j2

array([[1, 2, 3, 4]])

In [152]:
j3

array([[5, 6, 7, 8]])

In [146]:
i,j=np.array_split(e,2)

In [147]:
i

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [148]:
j

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])